// test_refdata.cpp — golden-table tests for the C++ port. The byte-level CLI
// and report surface is additionally differentially tested against the Python
// reference by tests/diff_cpp.py; this file pins the pure functions and the
// scheduling layer without needing Python or a toolchain.
//
// Sections:
//   1. pycompat: pyFloat (repr), round1, pyStr (json.dumps), pyIntParse,
//      pySplitLines, truncateRunes, pyStrip
//   2. runlean: parseLeanOutput (the ": error" / ": warning" / sorry scan)
//   3. module: moduleNameFromRel, topoLevels (chain / diamond / cycle)
//   4. engine: report text/JSON rendering against frozen reference outputs
//      (generated by tests/gen_ref2.py), verify/build scheduling with an
//      injected runLean
//   5. cli: frozen help/usage behaviors (exit codes + key lines)

#include <algorithm>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <filesystem>
#include <functional>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "cli.h"
#include "engine.h"
#include "module.h"
#include "pycompat.h"
#include "runlean.h"

using namespace leanoff;

namespace {

int failures = 0;
int checks = 0;

void check(bool ok, const std::string& what) {
    checks++;
    if (!ok) {
        failures++;
        std::fprintf(stderr, "FAIL %s\n", what.c_str());
    }
}

void checkEq(const std::string& got, const std::string& want, const std::string& what) {
    checks++;
    if (got != want) {
        failures++;
        std::fprintf(stderr, "FAIL %s\n", what.c_str());
        size_t i = 0;
        while (i < got.size() && i < want.size() && got[i] == want[i]) i++;
        std::fprintf(stderr, "  first diff at byte %zu (got %zu bytes, want %zu bytes)\n",
                     i, got.size(), want.size());
        size_t lo = i >= 20 ? i - 20 : 0;
        std::fprintf(stderr, "  got  [%zu..]: ", lo);
        for (size_t k = lo; k < got.size() && k < lo + 40; k++)
            std::fprintf(stderr, "%02x ", static_cast<unsigned char>(got[k]));
        std::fprintf(stderr, "\n  want [%zu..]: ", lo);
        for (size_t k = lo; k < want.size() && k < lo + 40; k++)
            std::fprintf(stderr, "%02x ", static_cast<unsigned char>(want[k]));
        std::fprintf(stderr, "\n");
        std::fprintf(stderr, "  got:  %s\n  want: %s\n", got.c_str(), want.c_str());
    }
}

// ---------------------------------------------------------------------------
// 1. pycompat

void testPyFloat() {
    const double vals[] = {0.0, 1.0, 0.984, 0.719, 1.5, 1e16, 1e15,
                           123456789.123, 0.0001, 0.00001, -2.5, 100.0, 3.14159,
                           1234567890123456.0, 0.1, 2.675, 3600.0, 0.03, 0.016};
    const char* want[] = {"0.0", "1.0", "0.984", "0.719", "1.5", "1e+16",
                         "1000000000000000.0", "123456789.123", "0.0001", "1e-05",
                         "-2.5", "100.0", "3.14159", "1234567890123456.0", "0.1",
                         "2.675", "3600.0", "0.03", "0.016"};
    for (size_t i = 0; i < sizeof(vals) / sizeof(vals[0]); i++) {
        checkEq(pyFloat(vals[i]), want[i], std::string("pyFloat #") + std::to_string(i));
    }
    checkEq(pyFloat(std::nan("")), "NaN", "pyFloat NaN");
    checkEq(pyFloat(HUGE_VAL), "Infinity", "pyFloat +inf");
    checkEq(pyFloat(-HUGE_VAL), "-Infinity", "pyFloat -inf");
}

void testRound1() {
    const double vals[] = {0.0, 1.0, 0.984, 0.719, 1.5, 1e16, 123456789.123,
                           0.0001, -2.5, 100.0, 3.14159, 0.1, 2.675, 3600.0,
                           0.03, 0.016};
    const double want[] = {0.0, 1.0, 1.0, 0.7, 1.5, 1e16, 123456789.1, 0.0,
                           -2.5, 100.0, 3.1, 0.1, 2.7, 3600.0, 0.0, 0.0};
    for (size_t i = 0; i < sizeof(vals) / sizeof(vals[0]); i++) {
        double got = round1(vals[i]);
        check(std::memcmp(&got, &want[i], 8) == 0,
              "round1 #" + std::to_string(i) + " (" + pyFloat(vals[i]) + ")");
    }
}

void testPyStr() {
    // (input, expected json.dumps output)
    struct Case {
        const char* in;
        const char* want;
    };
    const Case cases[] = {
        {"simple", "\"simple\""},
        {"with \"quote\"", "\"with \\\"quote\\\"\""},
        {"back\\slash", "\"back\\\\slash\""},
        {"tab\there", "\"tab\\there\""},
        {"nl\nhere", "\"nl\\nhere\""},
        {"ctrl\x01", "\"ctrl\\u0001\""},
        {"euro €", "\"euro \\u20ac\""},
        {"emoji 😀", "\"emoji \\ud83d\\ude00\""},
        {"math ß und ä", "\"math \\u00df und \\u00e4\""},
        {"cjk 中文", "\"cjk \\u4e2d\\u6587\""},
        {"del\x7f", "\"del\\u007f\""},
        {"", "\"\""},
    };
    for (const auto& c : cases) {
        checkEq(pyStr(c.in), c.want, std::string("pyStr ") + c.in);
    }
}

void testPyIntParse() {
    struct Case {
        const char* in;
        bool ok;
        long long v;
    };
    const Case cases[] = {
        {"1_0", true, 10}, {" 4 ", true, 4}, {"+4", true, 4}, {"-4", true, -4},
        {"x", false, 0}, {"1__0", false, 0}, {"_1", false, 0}, {"1_", false, 0},
        {"", false, 0}, {"0", true, 0}, {"  -12  ", true, -12},
    };
    for (const auto& c : cases) {
        long long v = 0;
        bool ok = pyIntParse(c.in, v);
        check(ok == c.ok && (!c.ok || v == c.v),
              std::string("pyIntParse '") + c.in + "'");
    }
    // Python's int is unbounded; long long overflows -> invalid (documented
    // divergence, only reachable via --jobs).
    long long v = 0;
    check(!pyIntParse("9999999999999999999999", v), "pyIntParse overflow");
}

void testSplitLinesTruncate() {
    // C++ hex escapes are greedy ("\x0be" would be 0xBE), so the VT/FF/FS/RS
    // bytes are split off with string concatenation. Python: 8 lines, no
    // trailing empty after the final separator.
    std::vector<std::string> lines = pySplitLines("a\r\nb\nc\rd\x0b" "e\x0c" "f\x1c" "g\x1d" "h\x1e");
    check(lines.size() == 8, "pySplitLines count");
    checkEq(lines[0], "a", "pySplitLines crlf");
    checkEq(lines[1], "b", "pySplitLines lf");
    checkEq(lines[2], "c", "pySplitLines cr");
    checkEq(lines[3], "d", "pySplitLines vt");
    checkEq(lines[7], "h", "pySplitLines rs");
    check(pySplitLines("a\n").size() == 1, "pySplitLines trailing sep");
    check(pySplitLines("").empty(), "pySplitLines empty");
    check(pySplitLines(u8"a\u2028b\u2029c").size() == 3, "pySplitLines unicode seps");

    checkEq(truncateRunes("abcdefghij", 160), "abcdefghij", "truncate under");
    checkEq(truncateRunes("abcdefghij", 4), "abcd", "truncate ascii");
    checkEq(truncateRunes(u8"日本語文", 2), u8"日本", "truncate runes");
    checkEq(truncateRunes("abc", 3), "abc", "truncate exact");
    checkEq(pyStrip("  x  "), "x", "pyStrip spaces");
    checkEq(pyStrip("\t\n\r x \v"), "x", "pyStrip mixed");
    checkEq(pyStrip(""), "", "pyStrip empty");
}

// ---------------------------------------------------------------------------
// 2. parseLeanOutput

void testParseLeanOutput() {
    const char* out =
        "A.lean:1:0: error: something\n"
        "A.lean:2:0: warning: deprecated\n"
        "A.lean:3:0: info: declaration uses 'sorry'\n"
        "A.lean:4:0: error: another error\n";
    LeanCounts c = parseLeanOutput(out);
    check(c.errors == 2, "parseLeanOutput errors");
    check(c.warnings == 1, "parseLeanOutput warnings");
    check(c.sorries == 1, "parseLeanOutput sorries");
    checkEq(c.first, "A.lean:1:0: error: something", "parseLeanOutput first");
    check(parseLeanOutput("").errors == 0, "parseLeanOutput empty");
    check(parseLeanOutput("plain text\n").first.empty(), "parseLeanOutput no errors");
}

// ---------------------------------------------------------------------------
// 3. modules

void testModuleName() {
    checkEq(moduleNameFromRel("A.lean"), "A", "moduleName simple");
    checkEq(moduleNameFromRel("Dir/Sub/Mod.lean"), "Dir.Sub.Mod", "moduleName nested");
    checkEq(moduleNameFromRel("Dots.In.Name.lean"), "Dots.In.Name", "moduleName dots");
}

void testTopoLevels() {
    auto mk = [](const char* n, std::vector<std::string> deps) {
        return Module{n, std::string("fake/") + n + ".lean", std::move(deps)};
    };
    // chain: C imports B imports A
    std::vector<Module> chain = {mk("A", {}), mk("B", {"A"}), mk("C", {"B"})};
    auto levels = topoLevels(chain);
    check(levels.size() == 3, "chain levels");
    checkEq(levels[0][0].name, "A", "chain level0");
    checkEq(levels[1][0].name, "B", "chain level1");
    checkEq(levels[2][0].name, "C", "chain level2");

    // diamond: D imports B and C; both import A
    std::vector<Module> dia = {mk("D", {"B", "C"}), mk("B", {"A"}), mk("C", {"A"}), mk("A", {})};
    levels = topoLevels(dia);
    check(levels.size() == 3, "diamond levels");
    checkEq(levels[0][0].name, "A", "diamond level0");
    check(levels[1].size() == 2, "diamond level1 size");
    checkEq(levels[1][0].name, "B", "diamond level1 first");
    checkEq(levels[1][1].name, "C", "diamond level1 second");
    checkEq(levels[2][0].name, "D", "diamond level2");

    // cycle: A <-> B
    std::vector<Module> cyc = {mk("A", {"B"}), mk("B", {"A"})};
    bool threw = false;
    try {
        topoLevels(cyc);
    } catch (const std::runtime_error& e) {
        threw = true;
        checkEq(e.what(), "leanoff: import cycle among: A, B", "cycle message");
    }
    check(threw, "cycle throws");
}

// ---------------------------------------------------------------------------
// 4. engine: report rendering (frozen outputs from tests/gen_ref2.py)

std::vector<Result> cannedResults() {
    std::vector<Result> rs;
    rs.push_back(Result{"A", true, 0, 0, 0, 0.05, ""});
    rs.push_back(Result{"Sub.C", false, 2, 1, 1, 1.25,
                        "Sub\\C.lean:3:0: error: unknown identifier 'foo'"});
    rs.push_back(Result{u8"中文.模块", false, 1, 0, 0, 10.0,
                        "error: 中文消息 with trailing spaces   "});
    rs.push_back(Result{"zz.last", true, 0, 3, 2, 3600.0, ""});
    return rs;
}

void testReportText() {
    std::ostringstream w;
    int rc = report(cannedResults(), 12.34, "text", w);
    check(rc == 1, "report text exit");
    checkEq(w.str(),
            "module   status err warn sorry    time\n"
            "A        PASS     0    0     0    0.1s\n"
            "Sub.C    FAIL     2    1     1    1.2s\n"
            "    Sub\\C.lean:3:0: error: unknown identifier 'foo'\n"
            "zz.last  PASS     0    3     2 3600.0s\n"
            "中文.模块    FAIL     1    0     0   10.0s\n"
            "    error: 中文消息 with trailing spaces\n"
            "\n"
            "4 modules: 2 failed, 3 errors, 4 warnings, 3 sorry  (12.3s wall)\n",
            "report text");
}

void testReportJSON() {
    std::ostringstream w;
    int rc = report(cannedResults(), 12.34, "json", w);
    check(rc == 1, "report json exit");
    checkEq(w.str(),
            "{\n"
            "  \"modules\": [\n"
            "    {\n"
            "      \"name\": \"A\",\n"
            "      \"ok\": true,\n"
            "      \"errors\": 0,\n"
            "      \"warnings\": 0,\n"
            "      \"sorries\": 0,\n"
            "      \"seconds\": 0.05,\n"
            "      \"first_error\": \"\"\n"
            "    },\n"
            "    {\n"
            "      \"name\": \"Sub.C\",\n"
            "      \"ok\": false,\n"
            "      \"errors\": 2,\n"
            "      \"warnings\": 1,\n"
            "      \"sorries\": 1,\n"
            "      \"seconds\": 1.25,\n"
            "      \"first_error\": \"Sub\\\\C.lean:3:0: error: unknown identifier 'foo'\"\n"
            "    },\n"
            "    {\n"
            "      \"name\": \"zz.last\",\n"
            "      \"ok\": true,\n"
            "      \"errors\": 0,\n"
            "      \"warnings\": 3,\n"
            "      \"sorries\": 2,\n"
            "      \"seconds\": 3600.0,\n"
            "      \"first_error\": \"\"\n"
            "    },\n"
            "    {\n"
            "      \"name\": \"\\u4e2d\\u6587.\\u6a21\\u5757\",\n"
            "      \"ok\": false,\n"
            "      \"errors\": 1,\n"
            "      \"warnings\": 0,\n"
            "      \"sorries\": 0,\n"
            "      \"seconds\": 10.0,\n"
            "      \"first_error\": \"error: \\u4e2d\\u6587\\u6d88\\u606f with trailing spaces   \"\n"
            "    }\n"
            "  ],\n"
            "  \"failed\": 2,\n"
            "  \"wall_seconds\": 12.3\n"
            "}\n",
            "report json");
}

void testReportEmpty() {
    std::ostringstream t;
    check(report({}, 0.04, "text", t) == 0, "empty text exit");
    checkEq(t.str(),
            "module    status err warn sorry    time\n"
            "\n"
            "0 modules: 0 failed, 0 errors, 0 warnings, 0 sorry  (0.0s wall)\n",
            "empty text");
    std::ostringstream j;
    check(report({}, 0.04, "json", j) == 0, "empty json exit");
    checkEq(j.str(),
            "{\n"
            "  \"modules\": [],\n"
            "  \"failed\": 0,\n"
            "  \"wall_seconds\": 0.0\n"
            "}\n",
            "empty json");
}

// Scheduling with an injected runLean: a fake toolchain over a temp tree.
// RunLeanFunc is a plain function pointer, so the fake records into
// file-scope statics.
std::vector<std::string> g_ran;  // module names in run order
std::string g_failName;         // module to fail; empty = all pass
std::string g_sorryName;        // module to report one sorry for

Result fakeRunLean(const std::string& exe, const std::string& root, const Module& mod,
                   const std::string& leanPath, const std::string& outOlean,
                   bool cwdRoot) {
    (void)exe; (void)root; (void)leanPath; (void)outOlean; (void)cwdRoot;
    g_ran.push_back(mod.name);
    bool bad = !g_failName.empty() && mod.name == g_failName;
    int sorries = (!g_sorryName.empty() && mod.name == g_sorryName) ? 1 : 0;
    return Result{mod.name, !bad, bad ? 1 : 0, 0, sorries, 0.001,
                  bad ? mod.name + ".lean:1:0: error: fake failure" : ""};
}

namespace fs = std::filesystem;

void putFile(const fs::path& p, const std::string& text) {
    std::FILE* f = std::fopen(p.u8string().c_str(), "wb");
    if (!f) return;
    std::fwrite(text.data(), 1, text.size(), f);
    std::fclose(f);
}

std::string joinNames(std::vector<std::string> names) {
    std::sort(names.begin(), names.end());
    std::string out;
    for (size_t i = 0; i < names.size(); i++) {
        if (i > 0) out += ",";
        out += names[i];
    }
    return out;
}

int countOccurrences(const std::string& s, const std::string& needle) {
    int n = 0;
    for (size_t pos = s.find(needle); pos != std::string::npos;
         pos = s.find(needle, pos + needle.size())) {
        n++;
    }
    return n;
}

// RAII temp directory under the system temp; ASCII-only names.
struct TempDir {
    fs::path path;
    bool ok = false;

    TempDir() {
        std::error_code ec;
        fs::path base = fs::temp_directory_path(ec);
        if (ec) return;
        for (int i = 0; i < 100; i++) {
            fs::path d = base / ("leanoff_test_" + std::to_string(i));
            if (fs::create_directory(d, ec)) {
                path = d;
                ok = true;
                return;
            }
        }
    }
    ~TempDir() {
        if (ok) {
            std::error_code ec;
            fs::remove_all(path, ec);
        }
    }
};

void testScheduling() {
    TempDir tmp;
    check(tmp.ok, "temp dir");
    if (!tmp.ok) return;

    // A imports sub.B; sub.B has no imports; sub.C imports sub.B.
    std::error_code ec;
    fs::path root = tmp.path / "proj";
    fs::create_directories(root / "sub", ec);
    putFile(root / "A.lean", "import sub.B\n");
    putFile(root / "sub" / "B.lean", "-- no imports\n");
    putFile(root / "sub" / "C.lean", "import sub.B\n");
    // Dummy executable: findToolchain only checks existence — the engine never
    // spawns lean because runLeanFn is injected.
    fs::path tc = tmp.path / "toolchain";
    fs::create_directories(tc, ec);
#ifdef _WIN32
    putFile(tc / "lean.exe", "");
#else
    putFile(tc / "lean", "");
#endif

    Options o;
    o.root = root.u8string();
    o.lean = tc.u8string();
    o.jobs = 2;
    o.format = "text";

    Engine eng;
    eng.runLeanFn = &fakeRunLean;
    std::ostringstream t;
    eng.out = &t;

    // verify: every module runs, all pass
    g_ran.clear(); g_failName.clear(); g_sorryName.clear();
    t.str("");
    int rc = eng.verify(o);
    check(rc == 0, "verify pass exit");
    checkEq(joinNames(g_ran), "A,sub.B,sub.C", "verify pass ran");
    check(countOccurrences(t.str(), "PASS") == 3, "verify pass PASSes");

    // verify: a failure does not cancel the remaining modules
    g_ran.clear(); g_failName = "sub.B";
    t.str("");
    rc = eng.verify(o);
    check(rc == 1, "verify fail exit");
    checkEq(joinNames(g_ran), "A,sub.B,sub.C", "verify fail ran all");
    check(countOccurrences(t.str(), "PASS") == 2, "verify fail PASSes");
    check(countOccurrences(t.str(), "FAIL") == 1, "verify fail FAILs");
    check(t.str().find("3 modules: 1 failed, 1 errors, 0 warnings, 0 sorry") !=
              std::string::npos,
          "verify fail summary");
    check(t.str().find("fake failure") != std::string::npos, "verify fail first error");

    // verify: a sorry fails unless --allow-sorry
    g_ran.clear(); g_failName.clear(); g_sorryName = "sub.C";
    t.str("");
    rc = eng.verify(o);
    check(rc == 1, "verify sorry exit");
    Options os = o;
    os.allowSorry = true;
    t.str("");
    rc = eng.verify(os);
    check(rc == 0, "verify allow-sorry exit");

    // verify: --filter narrows the module set
    g_ran.clear(); g_sorryName.clear();
    Options of = o;
    of.filter = "^A$";
    t.str("");
    rc = eng.verify(of);
    check(rc == 0, "verify filter exit");
    checkEq(joinNames(g_ran), "A", "verify filter ran");

    // build: level 0 = [sub.B], level 1 = [A, sub.C]; the olean tree appears
    // under <root>/.leanoff/olean
    g_ran.clear(); g_failName.clear();
    t.str("");
    rc = eng.build(o);
    check(rc == 0, "build pass exit");
    checkEq(joinNames(g_ran), "A,sub.B,sub.C", "build pass ran");
    check(fs::is_directory(root / ".leanoff" / "olean", ec), "build olean dir");

    // build: a failed level stops the build ??queued level-1 modules never run
    g_ran.clear(); g_failName = "sub.B";
    t.str("");
    rc = eng.build(o);
    check(rc == 1, "build fail exit");
    checkEq(joinNames(g_ran), "sub.B", "build fail stopped at level 0");
    check(t.str().find("1 modules: 1 failed") != std::string::npos,
          "build fail summary");

    // build: --out relocates the olean tree
    g_ran.clear(); g_failName.clear();
    Options oo = o;
    oo.out = (tmp.path / "elsewhere").u8string();
    t.str("");
    rc = eng.build(oo);
    check(rc == 0, "build out exit");
    check(fs::is_directory(tmp.path / "elsewhere", ec), "build out dir");

    // an import cycle is a build setup error; verify is unaffected
    fs::create_directories(tmp.path / "cyc", ec);
    putFile(tmp.path / "cyc" / "A.lean", "import B\n");
    putFile(tmp.path / "cyc" / "B.lean", "import A\n");
    Options oc = o;
    oc.root = (tmp.path / "cyc").u8string();
    bool threw = false;
    try {
        eng.build(oc);
    } catch (const std::runtime_error& e) {
        threw = true;
        check(std::string(e.what()).find("import cycle among: A, B") != std::string::npos,
              "cycle message");
    }
    check(threw, "build cycle throws");
    g_ran.clear();
    t.str("");
    rc = eng.verify(oc);
    check(rc == 0, "verify cycle ok");
    checkEq(joinNames(g_ran), "A,B", "verify cycle ran");
}

// ---------------------------------------------------------------------------
// 5. cli

void runCli(const std::vector<std::string>& args, std::ostringstream& out,
            std::ostringstream& err, int& rc) {
    out.str("");
    err.str("");
    rc = cliMain(args, out, err);
}

void testCli() {
    std::ostringstream out, err;
    int rc = 0;

    // help surfaces
    runCli({"-h"}, out, err, rc);
    check(rc == 0, "cli -h exit");
    check(out.str().rfind("usage: leanoff [-h] {verify,build} ...\n", 0) == 0, "cli -h usage");
    check(out.str().find("positional arguments:") != std::string::npos, "cli -h body");
    check(out.str().find("show this help message and exit\n") != std::string::npos, "cli -h tail");
    check(err.str().empty(), "cli -h stderr");

    runCli({"verify", "-h"}, out, err, rc);
    check(rc == 0, "cli verify -h exit");
    check(out.str().rfind("usage: leanoff verify [-h] [--root ROOT]", 0) == 0,
          "cli verify -h usage");
    check(out.str().find("--allow-sorry         do not fail on sorry\n") != std::string::npos,
          "cli verify -h body");

    runCli({"build", "-h"}, out, err, rc);
    check(rc == 0, "cli build -h exit");
    check(out.str().find("[--out OUT]") != std::string::npos, "cli build -h out");
    check(out.str().find("olean output directory (default:\n"
                        "                        <root>/.leanoff/olean)") != std::string::npos,
          "cli build -h out wrap");

    // missing / invalid subcommand
    runCli({}, out, err, rc);
    check(rc == 2, "cli no-args exit");
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: the following arguments are required: cmd\n",
            "cli no-args");

    runCli({"frobnicate"}, out, err, rc);
    check(rc == 2, "cli bad choice exit");
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: argument cmd: invalid choice: 'frobnicate' "
            "(choose from 'verify', 'build')\n",
            "cli bad choice");

    // unrecognized: reported by the top parser after a clean sub parse
    runCli({"verify", "--frob"}, out, err, rc);
    check(rc == 2, "cli sub unrecognized exit");
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: unrecognized arguments: --frob\n",
            "cli sub unrecognized");

    runCli({"verify", "extra", "more"}, out, err, rc);
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: unrecognized arguments: extra more\n",
            "cli sub positionals");

    // sub-level usage errors use the sub usage and prefix
    runCli({"verify", "--format", "xml"}, out, err, rc);
    check(rc == 2, "cli invalid choice exit");
    checkEq(err.str(),
            "usage: leanoff verify [-h] [--root ROOT] [--lean LEAN] [--lean-path LEAN_PATH]\n"
            "                      [--filter FILTER] [--jobs JOBS] [--allow-sorry]\n"
            "                      [--format {text,json}]\n"
            "leanoff verify: error: argument --format: invalid choice: 'xml' "
            "(choose from 'text', 'json')\n",
            "cli invalid choice");

    runCli({"verify", "--jobs", "x"}, out, err, rc);
    checkEq(err.str(),
            "usage: leanoff verify [-h] [--root ROOT] [--lean LEAN] [--lean-path LEAN_PATH]\n"
            "                      [--filter FILTER] [--jobs JOBS] [--allow-sorry]\n"
            "                      [--format {text,json}]\n"
            "leanoff verify: error: argument --jobs: invalid int value: 'x'\n",
            "cli invalid int");

    runCli({"verify", "--l", "."}, out, err, rc);
    checkEq(err.str(),
            "usage: leanoff verify [-h] [--root ROOT] [--lean LEAN] [--lean-path LEAN_PATH]\n"
            "                      [--filter FILTER] [--jobs JOBS] [--allow-sorry]\n"
            "                      [--format {text,json}]\n"
            "leanoff verify: error: ambiguous option: --l could match --lean, --lean-path\n",
            "cli ambiguous");

    runCli({"verify", "--root"}, out, err, rc);
    checkEq(err.str().substr(err.str().find("leanoff verify: error:")),
            "leanoff verify: error: argument --root: expected one argument\n",
            "cli expected one argument");

    runCli({"verify", "--allow-sorry=x"}, out, err, rc);
    checkEq(err.str().substr(err.str().find("leanoff verify: error:")),
            "leanoff verify: error: argument --allow-sorry: ignored explicit argument 'x'\n",
            "cli ignored explicit");

    // "--" semantics
    runCli({"--", "verify"}, out, err, rc);
    check(rc == 2, "cli -- verify exit");
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: argument cmd: invalid choice: '--' "
            "(choose from 'verify', 'build')\n",
            "cli -- verify");

    runCli({"verify", "--", "x"}, out, err, rc);
    checkEq(err.str(),
            "usage: leanoff [-h] {verify,build} ...\n"
            "leanoff: error: unrecognized arguments: -- x\n",
            "cli verify -- x");

    // left-to-right: help after a bad option still errors; before it wins
    runCli({"verify", "--format", "xml", "-h"}, out, err, rc);
    check(rc == 2, "cli error-then-help exit");
    runCli({"verify", "-h", "--format", "xml"}, out, err, rc);
    check(rc == 0, "cli help-then-error exit");

    // negative numbers and lone "-" are values, not options
    runCli({"verify", "--jobs", "-x"}, out, err, rc);
    checkEq(err.str().substr(err.str().find("leanoff verify: error:")),
            "leanoff verify: error: argument --jobs: expected one argument\n",
            "cli dash value refused");
}

}  // namespace

int main() {
    testPyFloat();
    testRound1();
    testPyStr();
    testPyIntParse();
    testSplitLinesTruncate();
    testParseLeanOutput();
    testModuleName();
    testTopoLevels();
    testReportText();
    testReportJSON();
    testReportEmpty();
    testScheduling();
    testCli();
    if (failures) {
        std::fprintf(stderr, "\n%d/%d checks failed\n", failures, checks);
        return 1;
    }
    std::printf("all %d checks passed\n", checks);
    return 0;
}
