package leanoff

import (
	"bytes"
	"strings"
	"testing"
)

// The text and JSON reports must match the Python reference byte for byte
// (modulo timings, which only lean itself determines). The want strings
// below were generated by running the Python reference implementation.

func TestReportText(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	results := []Result{
		{Name: "A", OK: true},
		{Name: "LongModuleName", Errors: 2, Warnings: 1, Sorries: 3, Seconds: 1.25, FirstError: "  X.lean:1:0: error: nope  "},
	}
	code := eng.report(results, 2.04, "text")
	if code != 1 {
		t.Fatalf("code = %d, want 1", code)
	}
	want := "module          status err warn sorry    time\n" +
		"A               PASS     0    0     0    0.0s\n" +
		"LongModuleName  FAIL     2    1     3    1.2s\n" +
		"    X.lean:1:0: error: nope\n" +
		"\n2 modules: 1 failed, 2 errors, 1 warnings, 3 sorry  (2.0s wall)\n"
	if buf.String() != want {
		t.Fatalf("text report mismatch:\n got: %q\nwant: %q", buf.String(), want)
	}
}

func TestReportTextShortNames(t *testing.T) {
	// width is the longest name, not a minimum of 8 (Python's default=8
	// only applies to an empty result list).
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	code := eng.report([]Result{{Name: "A", OK: true}}, 1.0, "text")
	if code != 0 {
		t.Fatalf("code = %d, want 0", code)
	}
	want := "module  status err warn sorry    time\n" +
		"A  PASS     0    0     0    0.0s\n" +
		"\n1 modules: 0 failed, 0 errors, 0 warnings, 0 sorry  (1.0s wall)\n"
	if buf.String() != want {
		t.Fatalf("text report mismatch:\n got: %q\nwant: %q", buf.String(), want)
	}
}

func TestReportTextEmpty(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	code := eng.report(nil, 0.0, "text")
	if code != 0 {
		t.Fatalf("code = %d, want 0", code)
	}
	want := "module    status err warn sorry    time\n" +
		"\n0 modules: 0 failed, 0 errors, 0 warnings, 0 sorry  (0.0s wall)\n"
	if buf.String() != want {
		t.Fatalf("text report mismatch:\n got: %q\nwant: %q", buf.String(), want)
	}
}

func TestReportTextFirstErrorTruncatedTo160Runes(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	long := strings.Repeat("é", 200) + ": error: nope"
	eng.report([]Result{{Name: "A", FirstError: long, Errors: 1}}, 1.0, "text")
	out := buf.String()
	idx := strings.LastIndex(out, "\n    ")
	if idx < 0 {
		t.Fatal("first_error line missing")
	}
	rest := out[idx+5:]
	end := strings.IndexByte(rest, '\n')
	if end < 0 {
		t.Fatal("first_error line not newline-terminated")
	}
	line := rest[:end]
	if line != strings.Repeat("é", 160) {
		t.Fatalf("first_error not truncated to 160 runes: %d runes", len([]rune(line)))
	}
}

func TestReportJSON(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	results := []Result{
		{Name: "A", OK: true, Seconds: 0.5},
		{Name: "B", Errors: 1, FirstError: "B.lean:1:0: error: nope", Seconds: 1.25},
	}
	code := eng.report(results, 3.04, "json")
	if code != 1 {
		t.Fatalf("code = %d, want 1", code)
	}
	want := `{
  "modules": [
    {
      "name": "A",
      "ok": true,
      "errors": 0,
      "warnings": 0,
      "sorries": 0,
      "seconds": 0.5,
      "first_error": ""
    },
    {
      "name": "B",
      "ok": false,
      "errors": 1,
      "warnings": 0,
      "sorries": 0,
      "seconds": 1.25,
      "first_error": "B.lean:1:0: error: nope"
    }
  ],
  "failed": 1,
  "wall_seconds": 3.0
}
`
	if buf.String() != want {
		t.Fatalf("json report mismatch:\n got: %q\nwant: %q", buf.String(), want)
	}
}

func TestReportJSONEmpty(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	code := eng.report(nil, 0.0, "json")
	if code != 0 {
		t.Fatalf("code = %d, want 0", code)
	}
	want := "{\n  \"modules\": [],\n  \"failed\": 0,\n  \"wall_seconds\": 0.0\n}\n"
	if buf.String() != want {
		t.Fatalf("json report mismatch:\n got: %q\nwant: %q", buf.String(), want)
	}
}

func TestReportResultsSortedByName(t *testing.T) {
	var buf bytes.Buffer
	eng := &Engine{Out: &buf}
	eng.report([]Result{{Name: "Z"}, {Name: "A"}, {Name: "M"}}, 1.0, "json")
	out := buf.String()
	a := strings.Index(out, `"name": "A"`)
	m := strings.Index(out, `"name": "M"`)
	z := strings.Index(out, `"name": "Z"`)
	if a < 0 || m < 0 || z < 0 || !(a < m && m < z) {
		t.Fatalf("modules not sorted by name:\n%s", out)
	}
}

func TestClassify(t *testing.T) {
	cases := []struct {
		r          Result
		allowSorry bool
		want       bool
	}{
		{Result{OK: true}, false, true},
		{Result{OK: false}, false, false},
		{Result{OK: true, Errors: 1}, false, false},
		{Result{OK: true, Sorries: 1}, false, false},
		{Result{OK: true, Sorries: 1}, true, true},
		{Result{OK: true, Warnings: 5}, false, true},
	}
	for _, c := range cases {
		if got := Classify(c.r, c.allowSorry); got != c.want {
			t.Errorf("Classify(%+v, %v) = %v, want %v", c.r, c.allowSorry, got, c.want)
		}
	}
}
